// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM-28rcbb2R4D7VmO7i2EeT68yAicXs_U',
    appId: '1:518585805470:web:dc69e65555a063c348a98f',
    messagingSenderId: '518585805470',
    projectId: 'ayangbeb-14897',
    authDomain: 'ayangbeb-14897.firebaseapp.com',
    storageBucket: 'ayangbeb-14897.appspot.com',
    measurementId: 'G-BQ6FJSPQVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKcwS2VD3sn6mEM2jDNoOZ2tLZFES8qGM',
    appId: '1:518585805470:android:be0bef80e4241d6748a98f',
    messagingSenderId: '518585805470',
    projectId: 'ayangbeb-14897',
    storageBucket: 'ayangbeb-14897.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAig9DBY-WzAH3Ty-dOKV0rzBSZ-IXvOAs',
    appId: '1:518585805470:ios:4c3d8c17e2116e7548a98f',
    messagingSenderId: '518585805470',
    projectId: 'ayangbeb-14897',
    storageBucket: 'ayangbeb-14897.appspot.com',
    iosBundleId: 'com.example.tugasAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAig9DBY-WzAH3Ty-dOKV0rzBSZ-IXvOAs',
    appId: '1:518585805470:ios:4c3d8c17e2116e7548a98f',
    messagingSenderId: '518585805470',
    projectId: 'ayangbeb-14897',
    storageBucket: 'ayangbeb-14897.appspot.com',
    iosBundleId: 'com.example.tugasAkhir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM-28rcbb2R4D7VmO7i2EeT68yAicXs_U',
    appId: '1:518585805470:web:742864c5ff13a21748a98f',
    messagingSenderId: '518585805470',
    projectId: 'ayangbeb-14897',
    authDomain: 'ayangbeb-14897.firebaseapp.com',
    storageBucket: 'ayangbeb-14897.appspot.com',
    measurementId: 'G-ZYLQJQZT3W',
  );
}
